insert into movies (title, releaseDate, rating, language, country, poster) values ('Godzilla vs. Hedorah (Gojira tai Hedorâ) (Godzilla vs. The Smog Monster) ', '1992-07-19', 5.7, 'Spanish', 'United Kingdom', 'Natoque.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Mother of Tears: The Third Mother (Terza madre, La)', '2008-03-21', 4.5, 'Swedish', 'Argentina', 'MorbiNonLectus.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Misadventures of Margaret, The', '1993-07-02', 4.4, 'Korean', 'United States', 'MusVivamusVestibulum.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Friday the 13th', '2007-12-29', 5.2, 'Italian', 'France', 'LigulaIn.gif');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Mannequin', '1999-05-18', 5.1, 'German', 'Germany', 'Molestie.gif');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Red Dawn', '1997-07-01', 7.4, 'Czech', 'Argentina', 'Metus.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Last Kiss, The', '2018-09-12', 8.1, 'Portuguese', 'Argentina', 'VelNisl.png');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Citizenfour', '2003-12-30', 6.1, 'Fijian', 'Argentina', 'NullamOrci.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('The Emperor of California', '1986-10-21', 6.5, 'Punjabi', 'United States', null);
insert into movies (title, releaseDate, rating, language, country, poster) values ('Babylon 5', '1987-07-09', 3.3, 'Tsonga', 'United States', 'LacusMorbi.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Adventures of Mark Twain, The', '2015-05-27', 3.0, 'Bulgarian', 'United States', 'AcLobortisVel.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Odd Man Out', '1999-01-01', 6.1, 'Swahili', 'United States', 'UtErat.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Drowning Mona', '1995-08-31', 6.1, 'Kazakh', 'Argentina', 'Scelerisque.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Linotype: The Film', '2018-04-12', 7.0, 'Bulgarian', 'France', null);
insert into movies (title, releaseDate, rating, language, country, poster) values ('Five People You Meet in Heaven, The', '1991-09-21', 7.9, 'Fijian', 'France', 'DonecPharetraMagna.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Point Men, The', '1990-09-15', 8.8, 'Thai', 'United States', 'CondimentumCurabiturIn.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Fear Clinic', '1987-05-30', 3.4, 'Estonian', 'France', 'ConvallisDuis.gif');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Love Finds Andy Hardy', '2005-02-07', 3.9, 'Bulgarian', 'United Kingdom', 'VulputateNonummy.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('My Mom''s New Boyfriend', '2004-02-14', 7.1, 'Filipino', 'United States', null);
insert into movies (title, releaseDate, rating, language, country, poster) values ('Endangered Species', '1999-01-12', 5.2, 'Hebrew', 'France', null);
insert into movies (title, releaseDate, rating, language, country, poster) values ('Postman Always Rings Twice, The', '1991-01-28', 4.7, 'Marathi', 'Argentina', null);
insert into movies (title, releaseDate, rating, language, country, poster) values ('Young Americans, The', '1983-10-08', 6.5, 'Georgian', 'France', 'LuctusTinciduntNulla.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Bag of Hammers, A', '1989-01-12', 5.4, 'Zulu', 'France', null);
insert into movies (title, releaseDate, rating, language, country, poster) values ('Gloria', '2018-04-03', 6.3, 'Latvian', 'France', 'FusceLacusPurus.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Snake of June, A (Rokugatsu no hebi)', '2005-07-29', 4.2, 'Portuguese', 'France', 'Proin.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Solino', '2010-07-07', 7.4, 'Armenian', 'Argentina', 'SapienQuisLibero.png');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Innocent, The', '1993-05-05', 4.4, 'Bislama', 'France', 'TinciduntNulla.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Coma', '2018-12-10', 3.9, 'Bislama', 'France', 'LobortisVelDapibus.jpeg');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Bleak House', '1994-03-03', 3.2, 'Yiddish', 'United Kingdom', 'Tristique.tiff');
insert into movies (title, releaseDate, rating, language, country, poster) values ('Veronica Mars', '1989-12-01', 4.1, 'Hiri Motu', 'United States', 'VestibulumAnte.jpeg');
